DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS products CASCADE;
DROP TABLE IF EXISTS reviews CASCADE;


CREATE TABLE users (
  id SERIAL PRIMARY KEY NOT NULL,
  cardholder VARCHAR(225) NOT NULL,
  card_number VARCHAR(225) NOT NULL,
  city VARCHAR(225) NOT NULL,
  country VARCHAR(225) NOT NULL,
  email VARCHAR(225) NOT NULL,
  expire_date VARCHAR(7) NOT NULL, -- "MM/YYYY" format
  state_province VARCHAR(225) NOT NULL,
  post_code VARCHAR(225) NOT NULL,
  street_address VARCHAR(225) NOT NULL
);

CREATE TABLE products (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(225) NOT NULL,
  price INTEGER NOT NULL DEFAULT 0,
  inventory INTEGER NOT NULL DEFAULT 0
);